### ISSUE TITLE
Execute method not supported?

### ISSUE THREAD

**Issue by gscott** [ExactTarget/Fuel-Node-SOAP#48]
I was trying to execute a `LogUnsubEvent` call and I time out.  Then I looked inside the code and see this:

https://github.com/ExactTarget/Fuel-Node-SOAP/blob/master/lib/fuel-soap.js#L331-L333

Am I out of luck? :)

**Comment by gscott** [comment]
@vernak2539 suggestion?

**Comment by vernak2539** [comment]
@gscott sorry for the delayed response. Unfortunately, I don't do much with SOAP. These guys would be best to ask. @dougwilson @aydrian @kellyjandrews

**Comment by dougwilson** [comment]
@vernak2539 I don't know too much about this SDK, but it looks from the OP that no one has implemented the execute method in this module. This basically sounds like a feature request for whoever maintains this module :)

Otherwise, it seems like you can use the `soapRequest` method to manually construct an Execute request, though I'm not familiar enough with this module's interface to know how to do that (besides it may require special handling to be added to `FuelSoap.prototype._parseResponse`).
```

**Comment by rawberg** [comment]
@gscott did you ever get the `LogUnsubEvent` event working? I'm able to create the xml payload successfully but always seem to get the same error back `Object reference not set to an instance of an object.`

**Comment by sataylor7** [comment]
@rawberg important to note that the `Name` and `Value` have to be capitalized
```
SoapClient.execute(
  "LogUnsubEvent",
  [
    {
      Name: "SubscriberID",
      Value: "subscriber id "
    },
    {
      Name: "SubscriberKey",
      Value: "whatever your subscriber key is"
    },
    {
      Name: "EmailAddress",
      Value: "superawesome@test.com"
    },
    {
      Name: "JobID",
      Value: 0
    },
    {
      Name: "ListID",
      Value: 0
    },
    {
      Name: "BatchID",
      Value: 0
    },
    {
      Name: "Reason",
      Value: "whatever reason"
    }
  ],
  (err, response) => {
    if (err) {
      // error here
      console.log(err);
      return;
    }

    // response.body === parsed soap response (JSON)
    // response.res === full response from request client
    console.log(response.body);
  }
);
```
